#Para escrever comentários ##
############################# Makefile ##########################
all: main.c listaord.c abb.c listaord_sentinela.c linkedListFREQ.c avl.c busca_binaria.c
	gcc -g -Wall main.c listaord.c abb.c listaord_sentinela.c linkedListFREQ.c avl.c busca_binaria.c

run: a.out
	./a.out
